# book settings
title: SAMueL Digital Twin bid
author: SAMueL Team
#logo: images/logo.png

#only build files specified in table of contents file
only_build_toc_files: true

execute:
  execute_notebooks: 'off' #cache output from .ipynb files for faster build or use auto
  timeout: -1 #no time restriction on notebook execution
  
launch_buttons:
  notebook_interface        : classic  
  binderhub_url             : ""
  
# Citation style, and rendering mermaid diagrams
sphinx:
  extra_extensions:
  - sphinxcontrib.mermaid
  
# pip install sphinxcontrib-mermaid 
