# book settings
title: SAMueL Patient Optimised Pathways (SAMueL-POP) bid
author: SAMueL Team
#logo: images/logo.png

#only build files specified in table of contents file
only_build_toc_files: true

execute:
  execute_notebooks: 'off' #cache output from .ipynb files for faster build or use auto
  timeout: -1 #no time restriction on notebook execution
  
launch_buttons:
  notebook_interface        : classic  
  binderhub_url             : ""
  
# Citation style, and rendering mermaid diagrams
sphinx:
  config:
    bibtex_default_style: unsrt
    bibtex_reference_style: super
  extra_extensions:
  - sphinxcontrib.mermaid
  
# pip install sphinxcontrib-mermaid 
